extends RefCounted
class_name MapQuads


static func build_from_single_corner(corner_map_data: Array) -> Array:
	# Assumption: corner_map_data represents the north-west / top-left corner.
	# The other corners are generated by rotating the same data.
	var nw := MapRotate.rotate_map_data(corner_map_data, 0)
	var ne := MapRotate.rotate_map_data(corner_map_data, 1)
	var se := MapRotate.rotate_map_data(corner_map_data, 2)
	var sw := MapRotate.rotate_map_data(corner_map_data, 3)

	return combine_quads(nw, ne, sw, se)


static func combine_quads(nw: Array, ne: Array, sw: Array, se: Array) -> Array:
	var corner_h := nw.size()
	if corner_h <= 0:
		return []

	var corner_w: int = nw[0].size()

	# This layout assumes a square quadrant. Otherwise the rotated quadrants do not
	# fit into a clean rectangular 2x2 map without extra rules.
	if corner_w != corner_h:
		push_warning("MapQuads.build_from_single_corner expects a square corner map. Result may not align perfectly.")

	var full_w := corner_w * 2
	var full_h := corner_h * 2
	var result := MapDataTools.create_empty_map(full_w, full_h)

	copy_map_into(result, nw, 0, 0)
	copy_map_into(result, ne, corner_w, 0)
	copy_map_into(result, sw, 0, corner_h)
	copy_map_into(result, se, corner_w, corner_h)

	return result


static func copy_map_into(target_map: Array, source_map: Array, offset_x: int, offset_y: int) -> void:
	for y in range(source_map.size()):
		if typeof(source_map[y]) != TYPE_ARRAY:
			continue

		var target_y := offset_y + y
		if target_y < 0 or target_y >= target_map.size():
			continue

		for x in range(source_map[y].size()):
			var target_x := offset_x + x
			if target_x < 0 or target_x >= target_map[target_y].size():
				continue

			var cell = source_map[y][x]
			if typeof(cell) == TYPE_DICTIONARY:
				target_map[target_y][target_x] = MapDataTools.duplicate_cell(cell)
			else:
				target_map[target_y][target_x] = cell
